server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:db.changelog/changelog.yml
    enabled: false
    password: 123
    user: admin
    url: jdbc:h2:mem:testdb
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    generate-ddl: false
  thymeleaf:
#    cache: false
    check-template: true
    prefix: classpath:/templates/
    check-template-location: true
    enabled: true
    suffix: .html
    enable-spring-el-compiler: true

  docker:
    compose:
      enabled: false
  devtools:
    livereload:
      enabled: true
    

    
